# Generated by Django 2.1.2 on 2018-10-28 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('original_title', models.CharField(max_length=140, verbose_name='Original title')),
                ('sinopse', models.TextField(blank=True, verbose_name='Sinopse')),
                ('release_date_of', models.DateField(verbose_name='Release date of')),
                ('type_anime', models.CharField(choices=[('shounen', 'Shounen'), ('shoujo', 'Shoujo'), ('bishoujo', 'Bishoujo'), ('seinen', 'Seinen'), ('josei', 'Josei'), ('kodomo', 'Kodomo'), ('gekiga', 'Gekiga'), ('ecchi', 'Ecchi'), ('mahou shoujo', 'Mahou Shoujo'), ('mahou shounen', 'Mahou Shounen'), ('mecha', 'Mecha'), ('harem', 'Harém'), ('yaoi', 'Yaoi'), ('yuri', 'Yuri'), ('shotacon', 'Shotacon'), ('lolicon', 'Lolicon'), ('hentai', 'Hentai')], max_length=50, verbose_name='Type')),
                ('number_of_episodes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of episodes')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'db_table': 'tb_anime',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('about_of', models.TextField(blank=True, verbose_name='About of')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'tb_author',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('original_title', models.CharField(max_length=140, verbose_name='Original title')),
                ('number_episode', models.PositiveSmallIntegerField(verbose_name='Number episode')),
                ('release_date_of', models.DateField(verbose_name='Release date of')),
                ('type_ep', models.CharField(choices=[('canon', 'CANON'), ('filler', 'FILLER')], max_length=6, verbose_name='Type episode')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Anime', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'db_table': 'tb_episode',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Action, Comedy', max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Genres',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.ManyToManyField(blank=True, related_name='anime_episodes', to='core.Episode', verbose_name='Episodes'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(to='core.Genres'),
        ),
    ]
